<?php
/**
 * @copyright Copyright (c) 2025 Magebit, Ltd. (https://magebit.com/)
 * @author    Magebit <info@magebit.com>
 * @license   MIT
 */

declare(strict_types=1);

/** @var AbstractBlock $block */
/** @var Escaper $escaper */

use Hyva\BraintreeHyvaCheckout\ViewModel\Braintree as BraintreeViewModel;
use Hyva\BraintreeHyvaCheckout\ViewModel\Payment\Method\ApplePay as ApplePayViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Magebit\VentaTheme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\AbstractBlock;

/** @var ViewModelRegistry $viewModels */
/** @var BraintreeViewModel $braintreeViewModel */
$braintreeViewModel = $viewModels->require(BraintreeViewModel::class);
/** @var ApplePayViewModel $applePayViewModel */
$applePayViewModel = $viewModels->require(ApplePayViewModel::class);
/** @var SvgIcons $icons */
$icons = $viewModels->require(SvgIcons::class);
?>

<div class="flex w-full items-center justify-center bg-gray-25">
    <div x-data="braintreeCheckoutApplepay"
         x-init="initApplePay"
         id="braintreeApplePay"
         wire:ignore
         @braintree-set-apple-token.window="onAppleTokenSet"
         @braintree-payment-error.window="onPaymentError">
        <template x-if="applePayToken">
            <span class="flex flex-col">
                <template x-if="withoutError">
                    <span class="py-5" x-text="paymentMessage"></span>
                </template>
            </span>
        </template>
        <template x-if="!applePayToken">
            <div class="w-full border-t border-gray-30 bg-gray-25 px-5 py-5 flex flex-col items-center justify-center">
                <div class="flex flex-col items-center justify-center">
                    <?= $icons->renderHtml('wallet', '', 71, 48); ?>
                    <p class="text-primary text-center pt-5">
                        <?= $escaper->escapeHtml(__('After clicking on the "Apple Pay" button you will be redirected to Apple Pay to complete your purchase securely.')) ?>
                    </p>
                </div>
            </div>
        </template>
    </div>
</div>
