<?php
/**
 * @copyright Copyright (c) 2025 Magebit, Ltd. (https://magebit.com/)
 * @author    Magebit <info@magebit.com>
 * @license   MIT
 */

declare(strict_types=1);

use Magebit\CheckoutComPayment\Magewire\Payment\Method\CheckoutComGooglePay;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var CheckoutComGooglePay $magewire */
/** @var Escaper $escaper */
?>

<div
    x-data="checkoutComGooglePay"
    x-init="init"
    data-component-name="<?= $escaper->escapeHtmlAttr($block->getNameInLayout()) ?>"
    data-payment-method="googlepay"
>
    <?= $escaper->escapeHtml(__('Please use Google Pay button to complete the order.')) ?>
</div>
