<?php
/**
 * @copyright Copyright (c) 2025 Magebit, Ltd. (https://magebit.com/)
 * @author    Magebit <info@magebit.com>
 * @license   MIT
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magebit\CheckoutComPayment\Helper\Config;
use Magebit\CheckoutComPayment\Magewire\Payment\Method\CheckoutComMBWayStatus;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var CheckoutComMBWayStatus $magewire */
/** @var ViewModelRegistry $viewModels */

/** @var Config $config */
$config = $viewModels->require(Config::class);
$statusText = $config->getMBWayStatusText();
$pollingInterval = $config->getMBWayPollingInterval();
?>

<div>
    <div class="mbway-status-page"
         <?php if ($magewire->isPolling): ?>
             wire:poll.<?= /* @noEscape */ $pollingInterval ?>ms="checkOrderStatus"
        <?php endif; ?>
    >
        <div class="flex flex-col h-full items-center justify-center text-center text-xl space-y-5">
            <p class="text-2xl">
                <?= $escaper->escapeHtml($statusText) ?>
            </p>
        </div>
    </div>
</div>
