<?php
/**
 * @copyright Copyright (c) 2025 Magebit, Ltd. (https://magebit.com/)
 * @author    Magebit <info@magebit.com>
 * @license   MIT
 */

declare(strict_types=1);

use Magebit\CheckoutComPayment\Magewire\Payment\Method\CheckoutComMBWayStatus;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var CheckoutComMBWayStatus $magewire */
?>

<div>
    <div class="mbway-status-page" wire:poll.5000ms="checkOrderStatus">
        <div class="flex flex-col h-full items-center justify-center text-center text-xl space-y-5">
            <p class="text-2xl">
                <?= $escaper->escapeHtml(__('Please complete the payment in your MB WAY app to avoid order cancellation.')) ?>
            </p>
        </div>
    </div>
</div>
