<?php
/**
 * @copyright Copyright (c) 2025 Magebit, Ltd. (https://magebit.com/)
 * @author    Magebit <info@magebit.com>
 * @license   MIT
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
?>

<div id="checkoutcom-googlepay-button-container" class="hidden h-10">
    <div id="ckoGooglePayButton-inNavigationContainer">
        <!-- Google Pay button will be rendered here -->
    </div>
</div>

<script>
    function toggleGooglePayButtons(showGooglePay) {
        const placeOrderButton = document.querySelector('.btn-place-order');
        const googlePayContainer = document.getElementById('checkoutcom-googlepay-button-container');

        if (placeOrderButton && googlePayContainer) {
            placeOrderButton.classList.toggle('hidden', showGooglePay);
            googlePayContainer.classList.toggle('hidden', !showGooglePay);
        }
    }

    window.addEventListener('checkout:payment:method-activate', event => {
        const isGooglePay = event.detail && event.detail.method === 'checkoutcom_google_pay';
        toggleGooglePayButtons(isGooglePay);
    });

    window.addEventListener('googlepay:button:created', () => {
        toggleGooglePayButtons(true);
    });
</script>
