<?php
/**
 * @copyright Copyright (c) 2025 Magebit, Ltd. (https://magebit.com/)
 * @author    Magebit <info@magebit.com>
 * @license   MIT
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
?>

<script>
    function showApplePay() {
        if (window.ApplePaySession && window.ApplePaySession.canMakePayments()) {
            const checkoutcomApplePayId = "payment-method-option-checkoutcom_apple_pay";
            const applePayContainer = document.getElementById(checkoutcomApplePayId);

            if (applePayContainer) {
                applePayContainer.classList.add('checkoutcom_apple_pay-visible');
            }
        }
    }

    function attachListener() {
        window.Magewire.hook('message.processed', (message, component) => {
            if (component.id === 'checkout.billing-details.address-list' || component.id === 'checkout.payment.methods') {
                showApplePay();
            }
        });

        showApplePay();
    }

    if (window.Magewire) {
        attachListener();
    } else {
        window.addEventListener('magewire:available', attachListener);
    }

    window.addEventListener('checkout:step:loaded', showApplePay)
</script>
